config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations",
    passwords: "user/passwords"
  }

  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
  get "visitors", to: "home#visitors"

  resources :coins, only: [:index]

  resources :portfolios, only: [:index, :show, :new, :create] do
    resources :holdings, only: [:new, :create, :update, :destroy]
  end

  resource :account, only: %i[ show ] do
    get "assets", on: :member
  end
end

app/models/holding.rb
class Holding < ApplicationRecord
  belongs_to :coin
  belongs_to :portfolio

  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  validate :unique_coin

  delegate :ticker, :rate, :icon, to: :coin
  delegate :account, to: :portfolio

  def deposit(amount)
    raise ArgumentError, "Amount must be positive" unless amount.positive?
    self.amount += amount
    self.save
  end

  def withdraw(amount)
    raise ArgumentError, "Not enough funds to withdraw" unless self.amount >= amount
    raise ArgumentError, "Amount must be positive" unless amount.positive?
    self.amount -= amount
    self.save
  end

  def update_value(amount)
    raise ArgumentError, "Amount must be positive" unless amount >= 0
    self.amount = amount
    self.save
  end

  def value
    (self.amount * self.rate).round(2)
  end

  private

  def unique_coin
    if portfolio&.holdings&.any? { |h| h.coin.id == coin.id && h.id != self.id}
      errors.add(:coin, "#{coin.ticker} is already in your portfolio. To add funds select the Deposit option.")
    end
  end

  def valid_update_amount?(amount)
    amount.positive? && amount.is_a?(Numeric)
  end
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portfolio, only: [:new, :create, :update, :destroy]
  before_action :set_coin, only: [:create]
  before_action :set_coins, only: [:new]
  before_action :set_holding, only: [:update]
  before_action :set_request_service, only: [:create, :update]

  def new
    @holding = Holding.new
  end

  def create
    @holding = @portfolio.holdings.build(holding_params)
    @coin.set_rate(@request_service)

    if @holding.save
      redirect_to @portfolio, notice: "#{@coin.ticker} added to Portfolio"
    else
      set_coins
      flash.now[:alert] = "ERROR: couldn't save coin"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    begin
      case operation_params[:operation]
      when "deposit"
        @holding.deposit(operation_params[:amount].to_d)
        redirect_to @portfolio, notice: "Successfully deposited #{operation_params[:amount].to_d} #{@holding.ticker}"
      when "withdraw"
        @holding.withdraw(operation_params[:amount].to_d)
        redirect_to @portfolio, notice: "Successfully withdrew #{operation_params[:amount].to_d} #{@holding.ticker}"
      when "update"
        @holding.update_value(operation_params[:amount].to_d)
        redirect_to @portfolio, notice: "Updated #{@holding.ticker} value to #{operation_params[:amount].to_d}"
      end
    rescue ArgumentError, StandardError => e
      set_portfolio
      set_coins
      flash.now[:error] = e.message
      render "portfolios/show", status: :unprocessable_entity
    end
  end

  def destroy
    holding = Holding.find(params[:id])
    if holding.destroy!
      redirect_to @portfolio, notice: "#{holding.ticker} removed from portfolio"
    end
  end

  private

  def set_portfolio
    @portfolio = Portfolio.find(params[:portfolio_id])
  end

  def holding_params
    params.require(:holding).permit(:coin_id, :amount)
  end

  def operation_params
    params.permit(:operation, :coin_id, :amount, :portfolio_id)
  end

  def set_coin
    @coin = Coin.find(params.dig(:holding, :coin_id))
  end

  def set_coins
    @coins = Coin.where(enabled: true).order(:ticker)
  end

  def set_holding
    @holding = Holding.find_by(
      portfolio_id: operation_params[:portfolio_id],
      coin_id: operation_params[:coin_id]
    )
  end

  def set_request_service
    conn = ApiConnectionService.build
    @request_service = ApiRequestsService.new(conn)
  end
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/views/holdings/_holding.html.erb
<div class="d-flex align-items-center justify-content-between ms-5">
  <div class="d-flex col">
    <%= image_tag holding.icon, size: "35x35", class: "align-self-center me-1" %>

    <div class="col d-flex flex-column m-2">
      <span class="fs-5"><%= holding.ticker %></span>
      <br>
      <span class="fs-6 text-white-50"><%= number_to_currency holding.rate %></span>
    </div>
  </div>

  <div class="col balance-details d-flex justify-content-start">
    <div class="d-flex flex-column">
      <span class="fs-5"><%= holding.amount %></span>
      <span class="fs-6 text-white-50"><%= number_to_currency holding.value %></span>
    </div>
  </div>

  <div class="col manage-cell">
    <%= link_to "Manage", root_path, class: "btn btn btn-outline-secondary" %>
  </div>
</div>

app/views/holdings/_manage_options.html.erb
<%= form_with url: portfolio_holding_path(portfolio), method: :put do |f| %>
  <div>
    <%= f.radio_button :operation, "deposit" %>
    <%= f.label :operation_deposit, "Deposit" %>
    <%= f.radio_button :operation, "withdraw" %>
    <%= f.label :operation_withdraw, "Withdraw" %>
    <%= f.radio_button :operation, "update" %>
    <%= f.label :operation_update, "Update" %>
  </div>
  <div>
    <%= f.collection_select :coin_id, coins, :id, :ticker, prompt: "Coin" %>
    <%= f.number_field :amount, step: 0.00001, placeholder: "Amount" %>
  </div>
  <div>
    <%= f.submit "Confirm", id: "confirm_button" %>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var coinSelect = document.getElementById("coin_id");
    var confirmButton = document.getElementById("confirm_button");

    if (coinSelect.value === "") {
      confirmButton.disabled = true;
    }
    
    coinSelect.addEventListener("change", function() {
      if (this.value === "") {
        confirmButton.disabled = true;
      } else {
        confirmButton.disabled = false;
      }
    });
  });
</script>

app/views/holdings/create.html.erb
<h1>Holdings#create</h1>
<p>Find me in app/views/holdings/create.html.erb</p>

app/views/holdings/new.html.erb
<%= render partial: "shared/form_errors", locals: { model: @holding } %>

<h1>New Holding</h1>

<%= form_with model: [@portfolio, @holding] do |f| %>
  <%= f.collection_select :coin_id, @coins, :id, :ticker, prompt: "Coin" %>
  <%= f.label :amount %>
  <%= f.number_field :amount, step: 0.000001, placeholder: 0.0 %>
  <%= f.submit "Add" %>
<% end %>

<%= link_to "Back", root_path %>