config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations",
    passwords: "user/passwords"
  }

  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
  get "visitors", to: "home#visitors"

  resources :coins, only: [:index]

  resources :portfolios, only: [:index, :show, :new, :create] do
    resources :holdings, only: [:new, :create, :update, :destroy]
  end

  resource :account, only: %i[ show ] do
    get "assets", on: :member
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :account
  has_many :holdings
  has_many :coins, through: :holdings

  validates :name, presence: true

  def refresh_rates(request_service)
    return if holdings.empty?

    coins = self.coins
    rates = request_service.get_rates(coins)
    coins.each do |coin|
      rate = rates.dig(coin.api_id.to_sym, :usd)
      coin.update!(rate: rate)
    end
  end

  def total_value
    holdings.reduce(0.0) do |total, holding|
      total += holding.amount * holding.coin.rate
      total
    end.round(2)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: %i[ new create index ]
  before_action :set_portfolio, only: %i[ show ]
  before_action :set_holdings, only: %i[ show ]
  before_action :set_request_service, only: %i[ show ]

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = @account.portfolios.build(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.turbo_stream { flash.now[:success] = "Portfolio created" }
        format.html { redirect_to @portfolio, success: "Portfolio created" }
      else
        flash.now[:error] = "ERROR: couldn't save portfolio"
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("form_title", partial: "shared/flash")
        end
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def index
    @portfolios = current_user.portfolios
  end

  def show
    # @portfolio.refresh_rates(@request_service)
    # @portfolio.holdings.reload
    @coins = @portfolio.holdings.map { |h| h.coin }
  end

  private

  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def set_account
    @account = current_user.account
  end

  def set_holdings
    @holdings = @portfolio.holdings.sort { |a, b| b.value <=> a.value }
  end

  def portfolio_params
    params.require(:portfolio).permit(:name)
  end

  def set_request_service
    conn = ApiConnectionService.build
    @request_service = ApiRequestsService.new(conn)
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_portfolio_list_item.html.erb
<%= link_to portfolio_path(portfolio), data: { turbo_frame: "portfolio_details" },
    class: "link-underline link-underline-opacity-0 text-white-50" do %>
  <div class="w-51 p-2 d-flex align-items-baseline link-accent row justify-content-between">
    <div class="col-md-7">
      <span class="fs-5 ms-1"><%= portfolio.name %></span>
    </div>
    <div class="col-md-5">
      <span class="fs-6"><%= number_to_currency portfolio.total_value %></span>
    </div>
  </div>
  <hr class="text-black">
<% end %>

app/views/portfolios/create.turbo_stream.erb
<%= turbo_stream.append "portfolios_console" do %>
  <%= render partial: "portfolio_list_item", locals: { portfolio: @portfolio } %>
<% end %>

<%= turbo_stream.replace "management_console" do %>
  <% @portfolio = Portfolio.new %>
  <%= render template: "portfolios/new" %>
<% end %>

<%= turbo_stream.replace "form_title" do %>
  <%= render partial: "shared/flash" %>
<% end %>

app/views/portfolios/index.html.erb
<%= turbo_frame_tag "portfolios_console" do %>
  <nav id="portfolios-menu" class="">

    <div class="d-flex justify-content-between">
      <h3 class="display-6 fs-3">Portfolios</h3>
      <%= link_to new_portfolio_path, class: "align-self-center text-white-50", 
                                      title: "Add Portfolio",
                                      id: "new_portfolio_button",
                                      data: { turbo_frame: "management_console" } do %>
        <i class="fa-solid fa-plus fa-xl link-accent"></i>
      <% end %>
    </div>

    <hr class="border border-black opacity-50">

    <% @portfolios.each do |p| %>
      <%= render partial: "portfolio_list_item", locals: { portfolio: p } %>
    <% end %>
  </nav>
<% end %>

app/views/portfolios/new.html.erb
<%= turbo_frame_tag "management_console" do %>
  <%= render partial: "shared/form_errors", locals: { model: @portfolio } %>

  <div id="container" class="container w-100">
    <div class="row d-flex align-content-around">
      
      <div class="w-100 text-center">
        <%= turbo_frame_tag "form_title" do %>
          <h3 class="display">New Portfolio</h3>
        <% end %>
      </div>
      
      <div class="text-center">
        <%= form_with model: @portfolio do |f| %>
          <div class="">
            <%= f.text_field :name, 
                             class: "form-control mb-3 mt-1 text-center", 
                             placeholder: "Portfolio name",
                             autofocus: true %>
          </div>
          <div>
            <%= f.submit "Create", class: "btn btn-outline-light w-100" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<section>
  <div id="manage-options">
    <%= render partial: "holdings/manage_options", locals: { portfolio: @portfolio, coins: @coins } %>
  </div>

  <br>
  
  <%= turbo_frame_tag "portfolio_details" do %>
    <div id="portfolio-container"
         class="container border border-dark rounded-2 p-3 bg-dark text-white w-70">
      <div id="portfolio-header"
           class="row align-baseline ms-5 d-flex align-items-end">
        <div class="col-md-4 ">
          <h3 class="display-6 fs-2"><%= @portfolio.name %></h3>
        </div>
        <div id="portfolio-balance" class="col-md-4 d-flex flex-column">
          <span class="text-white-50">Total:</span>
          <span class="fs-3"><%= number_to_currency @portfolio.total_value %></span>
        </div>

        <div id="portfolio-options" class="col-md-4">
          <%= link_to new_portfolio_holding_path(@portfolio), class: "text-white-50 ms-2 me-3", id: "new_holding_button" do %> 
            <i class="fa-solid fa-plus fa-2xl"></i>
          <% end %>
          <%= link_to root_path, class: "text-white-50" do %>
            <i class="fa-solid fa-gear fa-2xl"></i>
          <% end %>
        </div>
      </div>

      <hr class="border border-black opacity-50">

      <% if @portfolio.holdings.empty? %>
        <div class="text-center text-white-50 p-5">
          <p>Your portfolio is empty. Add coins to see them here</p>
        </div>

      <% else %>
        <div id="coins-table">
          <div id="list-header" class="row d-flex justify-content-around mb-3 ms-5">
            <div class="col-md-4">
              <span class="fs-5 text-white-50">Asset</span>
            </div>
            <div class="col-md-4">
              <span class="fs-5 text-white-50">Balance</span>
            </div>
            <div class="col-md-4"></div>
          </div>
          
          <div id="coins-list" >
            <% @holdings.each do |holding| %>
              <div class="coin-cell row mb-2 rounded-2 align-items-center" id="<%= holding.ticker.downcase %>_details">
                <%= render holding %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</section>