config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations",
    passwords: "user/passwords"
  }

  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
  get "visitors", to: "home#visitors"

  resources :coins, only: [:index]

  resources :portfolios, only: [:index, :show, :new, :create] do
    resources :holdings, only: [:new, :create, :update, :destroy]
  end

  resource :account, only: %i[ show ] do
    get "assets", on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!, only: [:index]

  def index
    if user_signed_in?
      @portfolios = current_user.account.portfolios.all
    else
      redirect_to visitors_path unless current_user
    end
  end

  def visitors; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav_bar.html.erb
<nav id="navigation-bar" class="navbar navbar-expand-lg bg-dark mb-4" data-bs-theme="dark">
  <div class="container-sm">
    <%= link_to "CryptoTracker", root_path, class: "navbar-brand display-1 fs-4" %>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <span class="text-white-50 align-self-center me-3">&lt;<%= current_user.email %>&gt;</span>
        <%= link_to root_path, class: "align-self-center", title: "Account" do %>
            <i class="fa-solid fa-user fa-xl nav-link"></i>
        <% end %>
        <li><%= button_to "Log out", destroy_user_session_path, { method: :delete, class: "nav-link btn btn-outline-dark" } %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<section>
  <div class="container mb-5">
    
    <div class="row mb-4">
      <div class="col-md-4">
        <%= turbo_frame_tag "account_console", src: account_path %>
      </div>

      <!-- MANAGEMENT CONSOLE -->
      <div class="col-md-8 bg-dark text-white d-flex justify-content-center align-items-center rounded-2">
        <%= turbo_frame_tag "management_console", class: "w-100" %>
      </div>
      <!-- -- -- -- -- -- -- -->
    </div>


    <div class="row">
      <div class="col-md-4 bg-dark text-white p-4 rounded-2">
        <%= turbo_frame_tag "portfolios_console", src: portfolios_path %>
      </div>

      <div class="col-md-8">
        <%= turbo_frame_tag "portfolio_details", src: assets_account_path %>
      </div>
    </div>
  </div>
</section>

app/views/home/visitors.html.erb
<h1>CryptoTracker</h1>

<p>A lightweight portfolio manager for your crypto currencies.</p>
<p>Simply add assets from a selected list and manage your funds.</p>

<h2><%= link_to "Create your account", new_user_registration_path %></h2>

<small>This is a personal study project, not intended for commercial use.</small>